In [118]:
from tkinter import *

In [119]:
from PIL import ImageTk,Image

In [120]:
import tkinter.messagebox

In [121]:
from tkinter import ttk

In [572]:
class database:
    def __init__(self,root):
        data = operation()
        data.conn()
        self.root = root
        self.root.title("ZOMATO HOTELS DATASET")
        self.root.geometry("1325x690")
        self.root.config(bg='yellow')
        first_value = StringVar()
        second_value = StringVar()
        third_value = StringVar()
        fourth_value = StringVar()
        fifth_value = StringVar()
        
        def close():
            print("close method called")
            close = tkinter.messagebox.askyesno("ZOMATO HOTELS DATASET","IF YES THEN BYE BYE")
            if close > 0:
                root.destroy()
                print("Method finished")
                return 
        
        def clear():
            print("clearing the text field")
            self.txtfirst_value.delete(0,END)
            self.txtsecond_value.delete(0,END)
            self.txtthird_value.delete(0,END)
            
        def clear_scroll():
            listing.delete(0,END)
            
        '''Saving data'''
        
        def check_first_value():
            if (len(first_value.get()) != 0):
                return True
            else:
                tkinter.messagebox.askyesno("ZOMATO HOTELS DATASET","ENTER CITY NAME TO RUN THE QUERY")
                return False
            
        def check_second_value():
            if (len(second_value.get()) != 0):
                return True
            else:
                tkinter.messagebox.askyesno("ZOMATO HOTELS DATASET","ENTER CUISINE NAME TO RUN THE QUERY")
                return False
            
        def check_third_value():
            if(len(third_value.get())!= 0):
                return True
            else:
                tkinter.messagebox.askyesno("ZOMATO HOTELS DATASET","ENTER RATING/PRICE TO RUN THE QUERY")

                
        def first_query():
            #listing.delete(0,END)
            if(check_first_value() == True and check_third_value()==True):
                print(first_value.get())
                first_query_data = data.first_query(first_value.get(), third_value.get())
                #print("*****************************************************8")
                #print(first_query_data)
                tree_insertion(first_query_data)
            
            #else:
             #    tkinter.messagebox.askyesno("ZOMATO HOTELS DATASET","ENTER CITY NAME TO GET THE RESTAURANTS WITH 4 RATING")
            #cols = list(first_query_data.columns)
            #tree["columns"] = cols
            '''for i in cols:
                tree.column(i,anchor="w")
                tree.heading(i, text=i, anchor='w')
            #for row in data.first_query():
             #   listing.insert(END, row)  
            
            for index, row in first_query_data.iterrows():
                tree.insert("",0,text=index, values=list(row))'''
                
        def tree_insertion(data_for_tree):
            cols = list(data_for_tree)
            tree["columns"] = cols
            for i in cols:
                tree.column(i, anchor="w")
                tree.heading(i, text=i, anchor='w')

            for index, row in data_for_tree.iterrows():
                tree.insert("",0,text=index,values=list(row))
                
        
        def second_query():
            if (check_second_value() == True):
                second_query_data = data.second_query(second_value.get())
                tree_insertion(second_query_data)
                    
            #else:
             #    tkinter.messagebox.askyesno("ZOMATO HOTELS DATASET","ENTER CUISINE NAME TO GET THE LIST OF RESTAURANTS")
                
            '''cols = list(data_collected.columns)
            
            
            tree["columns"] = cols
            for i in cols:
                tree.column(i, anchor="w")
                tree.heading(i, text=i, anchor='w')

            for index, row in data_collected.iterrows():
                tree.insert("",0,text=index,values=list(row))'''
            #self.buttonSaveField  = Button(tree, text='back', font=('areal',10,'bold'),height = 1, width = 30, bd= 4)
            #self.buttonSaveField.grid(row  = 0, column = 0)
            
        def third_query():
            third_query_data = data.third_query()
            tree_insertion(third_query_data)
            
        def fourth_query():
            if(check_first_value()==True):
                fourth_query_data = data.fourth_query(first_value.get())
                tree_insertion(fourth_query_data)
                
        def fifth_query():
            if(check_first_value()== True and check_third_value()== True):
                fifth_query_data = data.fifth_query(first_value.get(), third_value.get())
                tree_insertion(fifth_query_data)
                
        def sixth_query():
            if(check_second_value()==True):
                sixth_query_data = data.sixth_query(second_value.get())
                tree_insertion(sixth_query_data)
                
        def seventh_query():
            if(check_first_value()== True and check_second_value()== True):
                seventh_query_data = data.seventh_query(first_value.get(), second_value.get())
                tree_insertion(seventh_query_data)
                
        def eight_query():
            if(check_first_value()== True and check_second_value()== True and check_third_value()==True):
                eight_query_data = data.eight_query(first_value.get(), second_value.get(), third_value.get())
                tree_insertion(eight_query_data)
            
        def ninth_query():
            if(check_first_value()==True):
                ninth_query_data = data.ninth_query(first_value.get())
                tree_insertion(ninth_query_data)
            
        
        def back_to():
            for  i in tree.get_children():
                tree.delete(i)
            
            
        
        MainFrame = Frame(self.root,bg='red')
        MainFrame.grid()
        HeadFrame = Frame(MainFrame, bd=1, padx=20, pady=10, bg='white', relief=RIDGE)
        HeadFrame.pack(side=TOP)
        self.ITitle = Label(HeadFrame, font=('arial',15,'bold'), fg='red', text = 'ZOMATO DATA ANALYSIS PROJECT USING MONGODB BY DARSHAN DESAI - B00816526 AND SADHANA DESAI - B00811705', bg= 'white')
        self.ITitle.grid()
        BodyFrame = Frame(MainFrame, bd= 2, width = 1290, height = 400, padx= 30, pady = 20, bg ='white', relief=RIDGE)
        BodyFrame.pack(side=BOTTOM)
        LeftBody = LabelFrame(BodyFrame, bd= 2, width = 200, height = 120, padx= 20, pady = 10, bg ='yellow', relief=RIDGE, 
                              font=('arial', 15,'bold'), text='Checking details')
        LeftBody.pack(side=BOTTOM)
        QueryList = LabelFrame(BodyFrame, bd = 2, width = 1000, height = 120, padx= 20, pady = 10, bg= 'yellow', relief=RIDGE,
                              font=('arial',15,'bold'), text= 'Query List')
        QueryList.pack(side=TOP)
        RightBody = LabelFrame(BodyFrame, bd= 2, width = 1000, height = 400, padx= 20, pady = 10, bg ='yellow', relief=RIDGE, 
                              font=('arial', 15,'bold'), text='Check results')
        RightBody.pack(side=TOP)
        '''Adding information'''
        self.labelfirst_value = Label(LeftBody, bd = 2, font=('arial', 12,'bold'), text='Enter City Name Here', padx = 2,pady=2, bg ='white', fg= 'blue')
        self.labelfirst_value.grid(row= 0, column = 0, sticky=W)
        self.txtfirst_value = Entry(LeftBody, font=('arial',15,'bold'), textvariable = first_value, width = 18)
        self.txtfirst_value.grid(row = 0, column = 1, sticky = W)
        
        self.labelsecond_value = Label(LeftBody, bd = 2, font=('arial', 12,'bold'), text='Enter Cuisine/ Rating Here', padx = 2,pady=2, bg ='white', fg= 'blue')
        self.labelsecond_value.grid(row= 1, column= 0, sticky = W)
        self.txtsecond_value = Entry(LeftBody, font=('arial',15,'bold'), textvariable = second_value, width = 18)
        self.txtsecond_value.grid(row=1, column = 1, sticky= W)
        
        self.labelthird_value = Label(LeftBody, bd = 2, font=('arial', 12,'bold'), text='Enter Price/ Rating Here', padx = 2,pady=2, bg ='white', fg= 'blue')
        self.labelthird_value.grid(row= 2, column= 0, sticky = W)
        self.txtthird_value = Entry(LeftBody, font=('arial',15,'bold'), textvariable = third_value, width = 18)
        self.txtthird_value.grid(row=2, column = 1, sticky= W)
        
        #self.empty = Label(LeftBody, padx = 2,pady=2)
        #self.empty.grid(row=4, column = 0, sticky=W)
        
        #self.empty1 = Label(LeftBody, padx = 2,pady=2)
        #self.empty1.grid(row=5, column = 0, sticky=W)
        
        #self.empty2 = Label(LeftBody, padx = 2,pady=2)
        #self.empty2.grid(row=7, column = 0, sticky=W)
        
        #self.empty3 = Label(LeftBody, padx = 2,pady=2)
        #self.empty3.grid(row=9, column = 0, sticky=W)
        
        '''Menu for options'''
        
        '''List Scroller'''
        scroll_query = Scrollbar(QueryList)
        scroll_query.grid(row=0, column=1, sticky='ns')
        
        QuerySelect = Listbox(QueryList, height = 6, width = 130, bg='yellow', relief=RIDGE,
                             font=('arial',13,'italic','bold'), xscrollcommand = scroll_query.set)
       
        
        scroll_query.config(command=QuerySelect.xview)
        
        QuerySelect.insert(1,"1 Give the minimum rating and city name to get the list of restaurants which follows it.")
        QuerySelect.insert(2,"2 Enter the cuisine name and get the restaurants which has that cuisines.")
        QuerySelect.insert(3,"3 From the dataset (where each hotel has multiple cuisine) get unique cuisines in the dataset.")
        QuerySelect.insert(4,"4 For the selected city get the average cost for all cuisines. Which are available at the restaurants of given city.")
        QuerySelect.insert(5,"5 Enter the name of city and minimum rating above which you want to have the restaurants.")
        QuerySelect.insert(6,"6 Get the average number rating for restaurants which has minimum 'x' number of outlets. Where x is provided by user.")
        QuerySelect.insert(7,"7 Checking if online booking is available at the restaurant for the given cuisine and city and get sorted results by the average cost and rating.")
        QuerySelect.insert(8,"8 For the given price and cuisine and city get the suitable restaurants.")
        QuerySelect.insert(9,"9 Getting total number of hotels per cuisine for the City. The city will be provided by user.")
        QuerySelect.grid(row=0,column=0, padx=8)
        
        

        
        '''Scroller'''
        scroll = Scrollbar(RightBody)
        scroll.grid(row=0, column=1, sticky='ns')
        
        listing = Listbox(RightBody, width = 80, height = 16, font=('arial',12,'bold'), xscrollcommand = scroll.set)
        listing.grid(row=0, column= 0, padx=8)
        scroll.config(command=listing.xview)
        
        '''Tree View'''
        tree = ttk.Treeview(listing)
        tree.grid(row = 0, column=0)
        
        #self.exit = Button(LeftBody, text='Exit', command = back_to)
        #self.exit.grid(row=2,column=0)
        
        
        '''Buttons'''
        self.buttonSave  = Button(LeftBody, text='First Query', font=('arial',10,'bold'),height = 1, width = 15, bd= 2, command = first_query)
        self.buttonSave.grid(row  = 0, column = 2)
            
        self.buttonclose  = Button(LeftBody, text='Close', font=('arial',10,'bold'),height = 1, width = 15, bd= 2, command= close )
        self.buttonclose.grid(row = 1, column= 6)
        
        
        self.buttonclear  = Button(LeftBody, text='Clear', font=('arial',10,'bold'),height = 1, width = 20, bd= 4, command= clear )
        self.buttonclear.grid(row  = 3, column = 1)
        
        self.buttonclearscroll  = Button(RightBody, text='Clear', font=('arial',10,'bold'),height = 1, width = 30, bd= 4, command= back_to )
        self.buttonclearscroll.grid(row  = 2, column = 0)
        
        self.buttonSecond  = Button(LeftBody, text='Second Query', font=('arial',10,'bold'),height = 1, width = 15, bd= 2, command = second_query)
        self.buttonSecond.grid(row  = 0, column = 3)
        
        self.buttonThird = Button(LeftBody, text='Third Query', font=('arial',10,'bold'),height = 1, width = 15, bd= 2, command = third_query)
        self.buttonThird.grid(row  = 0, column = 4)
        
        self.buttonFourth = Button(LeftBody, text='Fourth Query', font=('arial',10,'bold'),height = 1, width = 15, bd= 2, command = fourth_query)
        self.buttonFourth.grid(row  = 0, column = 5)
        
                
        self.buttonFifth = Button(LeftBody, text='Fifth Query', font=('arial',10,'bold'),height = 1, width = 15, bd= 2, command = fifth_query)
        self.buttonFifth.grid(row  = 0, column = 6)
        
        self.buttonSixth = Button(LeftBody, text='Sixth Query', font=('arial',10,'bold'),height = 1, width = 15, bd= 2, command = sixth_query)
        self.buttonSixth.grid(row  = 1, column = 2)
        
        self.buttonSeventh = Button(LeftBody, text='Seventh Query', font=('arial',10,'bold'),height = 1, width = 15, bd= 2, command = seventh_query)
        self.buttonSeventh.grid(row  = 1, column = 3)
        
        self.buttonEight = Button(LeftBody, text='Eight Query', font=('arial',10,'bold'),height = 1, width = 15, bd= 2, command = eight_query)
        self.buttonEight.grid(row  = 1, column = 4)
        
        self.buttonNinth = Button(LeftBody, text='Ninth Query', font=('arial',10,'bold'),height = 1, width = 15, bd= 2, command = ninth_query)
        self.buttonNinth.grid(row  = 1, column = 5)

In [30]:
import pymongo

In [31]:
import pandas as pd

In [ ]:
####Dataset operation###

In [573]:
class operation:
    def __init__(self):
        self.myclient = pymongo.MongoClient("mongodb://localhost:27017/")
        self.mydb = self.myclient["zomato"]
        self.col = self.mydb['hotels']
        
    def conn(self):
        print("calling connection")
        #myclient = pymongo.MongoClient("mongodb://localhost:27017/")
        #mydb = myclient["zomato"]
        #col = mydb['hotels']
        x = self.col.find()

        self.myclient.close()
        
    def first_query(self, get, rating):
        #myclient = pymongo.MongoClient("mongodb://localhost:27017/")
        #mydb = myclient["zomato"]
        #col = mydb['hotels']
        restaurants = self.col.find({"Aggregate rating":{"$gte":float(rating)},  "City": {'$regex': get, '$options':'i'}})
        results_rating_for_city = []
        for i in restaurants:
            results_rating_for_city.append(i)
        first_dataframe = pd.DataFrame(results_rating_for_city)
        first_dataframe = first_dataframe[['Restaurant Name','Address','Votes','Average Cost for two','Aggregate rating']]
        first_dataframe = first_dataframe.sort_index(ascending=False)
        #print(re)
        return first_dataframe
    
    def second_query(self, get):
        #myclient = pymongo.MongoClient("mongodb://localhost:27017/")
        #mydb = myclient["zomato"]
        #col = mydb['hotels']
        second_dataframe = pd.DataFrame(list(self.col.find({'Cuisines':{'$regex': get, '$options':'i'}})))
        second_dataframe = second_dataframe[['Restaurant Name','Cuisines','Address','City','Average Cost for two','Aggregate rating']]
        second_dataframe = second_dataframe.sort_index(ascending=False)
        
        #list_element = pd.DataFrame(list(self.col.find()))
        #list_element = list_element.sort_index(ascending=False)
        #print(list_element)
        
        return second_dataframe
    
    def third_query(self):
        '''In the datframe cuisines for the restaurants are given in single column we are having a task
        to separate them and show only unique cuisines over the whole dataset
        '''
        cuisine_list = self.col.distinct("Cuisines")
        cuisines = [i.split(',')[0] for i in cuisine_list]
        results = []
        for i in cuisines:
            if i not in results:
                results.append(i)
                
        cuisines_data = pd.DataFrame(results, columns=['Cuisines'])
        cuisines_data = cuisines_data.sort_index(ascending= False)
        return cuisines_data
    
    def fourth_query(self, get):
        '''User will provide city name for which he want's the average cost for two '''
        get_dataframe = self.third_query()
        get_dataframe = get_dataframe['Cuisines'].values.tolist()
        get_indexes = []
        for cuisine in get_dataframe:
            get_indexes.append(self.col.aggregate([{'$match':{'$and':[{'Cuisines':{'$regex':cuisine,'$options':'i'}}, 
                                                                      {'City':{'$regex':get,'$options':'i'}}]}},{'$group': {'_id':{'City':'$City','Cuisine':cuisine}, 'Average cost':{'$avg':'$Average Cost for two'}}}, {'$sort':{'Average cost':1}}]))
            
        result_dataframe = pd.DataFrame(list(get_indexes), columns=['Cuisines'])
        result_dataframe = result_dataframe.dropna()
        result_dataframe = result_dataframe.reset_index(drop=True)
        result_dataframe = result_dataframe['Cuisines'].apply(pd.Series)
        collect_avg_cost = result_dataframe
        result_dataframe = result_dataframe['_id'].apply(pd.Series)
        for_print = pd.concat([result_dataframe['Cuisine'],collect_avg_cost['Average cost']], axis = 1)
        for_print = for_print.sort_values(by=['Average cost'])
        for_print = for_print.reset_index(drop= True)
        for_print = for_print.sort_index(ascending= False)
        
        return for_print
    
    def fifth_query(self, city_val, rating_val):
        print(rating_val)
        '''In this will take only rating from user and kept voting count greater than 100 default'''
        fifth_query_list =  self.col.find({'$and':[{'City':{'$regex':city_val, '$options':'i'}},{'Aggregate rating':{'$gte':float(rating_val)}},
                                                        {'Votes':{'$gte':100}}]}).sort([('Aggregate rating',-1),('Average Cost for two', 1)])
        fifth_query_dataframe = pd.DataFrame(list(fifth_query_list))

        fifth_query_dataframe = fifth_query_dataframe[['Restaurant Name','Average Cost for two','Aggregate rating']]
        fifth_query_dataframe = fifth_query_dataframe.sort_index(ascending = False)
        
        return fifth_query_dataframe
    
    def sixth_query(self, get):
        '''Finding restaurants all over the world from dataset and will take the count for minimum restaurants outlet
           from user
        '''
        sixth_query_list = self.col.aggregate([{'$group':{'_id':'$Restaurant Name', 'count':{'$sum':1}, 'rating':{'$avg':{'$ifNull':['$Aggregate rating',0]}}}},{'$match':{'count':{'$gt':int(get)}}},{'$sort':{'count':-1}}])
        sixth_query_dataframe = pd.DataFrame(list(sixth_query_list))
        sixth_query_dataframe.rename(columns = {'_id':'Restaurant Name','count':'Number of Outlets', 'rating':'Avaerage Rating'}, inplace= True)
        
        sixth_query_dataframe = sixth_query_dataframe.sort_index(ascending = False)
        
        return sixth_query_dataframe
    
    def seventh_query(self, city_val, cuisine_val):
        '''Checking option for table booking with rating and cost provided'''
        seventh_query_list = self.col.find({'$and':[{'Cuisines':{'$regex': cuisine_val, '$options':'i'}}, {'City':{'$regex':city_val, '$options':'i'}},
                                      {'Has Table booking':'Yes'}]}).sort([('Aggregate rating',-1),('Average Cost for two',1)])
        seventh_query_dataframe = pd.DataFrame(list(seventh_query_list))
        
        seventh_query_dataframe = seventh_query_dataframe[['Restaurant Name','Address','Has Table booking','Average Cost for two','Aggregate rating']]
        
        seventh_query_dataframe = seventh_query_dataframe.sort_index(ascending= False)
        
        return seventh_query_dataframe
    
    def eight_query(self, city_val, cuisine_val, price_val):
        '''Getting unique list of cities witout distinct keyword as we know 'distinct' keyword takes high i/o access '''
        #cities_list = pd.DataFrame(list(self.col.aggregate([{'$group':{'_id':'$City'}},{'$sort':{'City':1}}])))
        #cities_list.rename(columns={'_id':'CITY'}, inplace=True)
        
        #cities_list = cities_list.sort_values('CITY', ascending = True).reset_index()
        #cities_list = cities_list.sort_index(ascending= False)
        #cities_list = cities_list[['CITY']]
        
        match_hotels = self.col.aggregate([{'$match':{'$and':[{'Cuisines':{'$regex':cuisine_val ,'$options':'i'}}, 
                                                                      {'City':{'$regex':city_val ,'$options':'i'}}, {'Average Cost for two':{'$lte':int(price_val)}}]}}, {'$sort':{'Average Cost for two':1}}])
        
        calc_len = list(match_hotels)
        
        if (len(calc_len) == 0):
            cities = {'Restaurant Name':[0], 'Address':[0], 'Cuisines':[0], 'Average Cost for two':[0], 'Aggregate rating':[0]}
            cities_list = pd.DataFrame(cities, columns = ['Restaurant Name','Address','Cuisines','Average Cost for two','Aggregate rating'])
            
            
        else:
            hotel_dataframe = pd.DataFrame(calc_len)
            
            cities_list = hotel_dataframe[['Restaurant Name','Address','Cuisines','Average Cost for two','Aggregate rating']]
        
        
        count_of_hotels = len(cities_list.index)
        if count_of_hotels < 3:
            optional_cuisine = self.ninth_query(city_val)
            
            if optional_cuisine['Total Count'].max() > 3:
                new_data = optional_cuisine[optional_cuisine['Total Count'] == optional_cuisine['Total Count'].max()]
                cities_list = pd.concat([cities_list, new_data], ignore_index=True,sort=True)
                cities_list = cities_list.sort_index(ascending=False)
                cities_list = cities_list[['Restaurant Name','Address','Cuisines','Average Cost for two','Aggregate rating','Cuisine Type','Total Count']]
                cities_list = cities_list.fillna(0)
                cities_list.iloc[0, cities_list.columns.get_loc('Restaurant Name')] = 'Check for popular cuisine in this area'
                
        else:
            cities_list = cities_list.sort_index(ascending=False)
                
        
        return cities_list
    
    def ninth_query(self, get):
        '''Variety of hotels over the city'''
        list_of_hotels_count = []
        list_of_cuisine = self.third_query()
        list_of_cuisine = list_of_cuisine['Cuisines'].values.tolist()
        for cuisine in list_of_cuisine:
            list_of_hotels_count.append(self.col.aggregate([{'$match':{'$and':[{'Cuisines':{'$regex':cuisine, '$ne':None}},{'City':{'$regex':get,'$options':'i'}}]}},
                                                {'$group':{'_id':cuisine, 'count':{'$sum':1}}}, {'$sort':{'count':1}}]))
        
        counting_hotels = pd.DataFrame(list(list_of_hotels_count), columns=['List'])
        counting_hotels = counting_hotels['List'].apply(pd.Series)
        counting_hotels= counting_hotels.dropna().reset_index()
        counting_hotels.rename(columns={'_id':'Cuisine Type', 'count':'Total Count'}, inplace= True)
        counting_hotels = counting_hotels.sort_values(by=['Total Count'], ascending= False).reset_index()
        counting_hotels = counting_hotels.sort_index(ascending=False)
        counting_hotels = counting_hotels[['Cuisine Type','Total Count']]
        
        
        
        return counting_hotels

In [574]:
if __name__ == '__main__':
    root=Tk()
    application = database(root)
    root.mainloop()

calling connection